services:
  - type: web
    name: busnow-api
    env: node
    plan: free
    region: singapore
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start:prod
    rootDir: ./
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: busnow-postgres
          property: connectionString

databases:
  - name: busnow-postgres
    plan: free
